[package]
name = "juliet"
version = "0.1.0"
edition = "2021"
authors = [ "Marc Brinkmann <marc@casperlabs.io>" ]

[dependencies]
bytes = "1.4.0"
thiserror = "1.0.40"

[dev-dependencies]
proptest = "1.1.0"
proptest-attr-macro = "1.0.0"
proptest-derive = "0.3.0"
