name: juliet crate tests
run-name: juliet crate tests triggered by ${{ github.actor }}
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - run: nix-shell --pure --command ./test.sh
